---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: lil-eks
  region: eu-north-1
  tags:
    project: linkedin-learning

nodeGroups:
  - name: worker-node
    instanceType: t3.micro
    desiredCapacity: 3
